spring:

  server:
    port: ${SERVER_PORT:5000}


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  mongodb:
    uri: ${MONGO_URI}

  data:
    mongodb:
      auto-index-creation: true
  
  security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
                        client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
                        #scope: profile, email
                        #redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                #provider:
                    #google:
                        #authorization-uri: https://accounts.google.com/o/oauth2/auth
                        #token-uri: https://oauth2.googleapis.com/token
                        #user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


frontend:
  url: ${FRONTEND_URL}

# Stripe API Keys
stripe:
  public-key: ${STRIPE_PUBLIC_KEY}
  private-key: ${STRIPE_SECRET_KEY}