spring:
    application:
        name: backend

    output:
        ansi:
            enabled: ALWAYS


logging:
    level:
        "[org.springframework.data.mongodb]": DEBUG
        "[com.skillstorm]": DEBUG


server: 
    port: 8282
