spring:
    application:
        name: backend

    output:
        ansi:
            enabled: ALWAYS

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
                        client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
                        #scope: profile, email
                        #redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                #provider:
                    #google:
                        #authorization-uri: https://accounts.google.com/o/oauth2/auth
                        #token-uri: https://oauth2.googleapis.com/token
                        #user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo



logging:
    level:
        "[org.springframework.data.mongodb]": DEBUG
        "[com.skillstorm]": DEBUG



server:
    port: ${SERVER_PORT:8282}
    

frontend:
    url: http://localhost:3000
    
stripe:
    public-key: ${STRIPE_PUBLIC_KEY}
    private-key: ${STRIPE_SECRET_KEY}
